# Deploytag
executors:
  deploytag:
    resource_class: small
    docker:
      - image: 895963939461.dkr.ecr.us-west-2.amazonaws.com/deploytag:master
        aws_auth:
          aws_access_key_id: $BUILD_RUNNER_ECR_ACCESS_KEY
          aws_secret_access_key: $BUILD_RUNNER_ECR_SECRET_KEY

# Jobs
version: 2.1
jobs:
  build_and_deploy:
    executor: deploytag
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build and deploy vault image
          command: |
            deploytag --actions build \
              --registry 895963939461.dkr.ecr.us-west-2.amazonaws.com/newrelic-autodiscover \
              --region us-west-2 \
              --role arn:aws:iam::895963939461:role/ci-role \
              --userole
            
            deploytag --actions deploy \
              --chart deploy/minikube \
              --env sandbox \
              --namespace default \
              --region us-west-2 \
              --role arn:aws:iam::895963939461:role/ci-role \
              --userole

workflows:
  version: 2
  build:
    jobs:
      - build_and_deploy:
          context: cicd
          filters:
            branches:
              only:
                - master