---
apiVersion: batch/v1
kind: Job
metadata:
  name: nri-discovery-kubernetes
  namespace: default
  labels:
    app: nri-discovery-kubernetes
spec:
  template:
    metadata:
      labels:
        app: nri-discovery-kubernetes
    spec:
      serviceAccountName: newrelic
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: nri-discovery-kubernetes
          image: 895963939461.dkr.ecr.us-west-2.amazonaws.com/newrelic-autodiscover:master
          securityContext:
            privileged: true
      restartPolicy: Never